runtime: nodejs18

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: production
