export const supportedDevices = [
  {
    id: "apple-watch",
    name: "Apple Watch",
    icon: "⌚",
    description: "Sync your Apple Health data",
    fileTypes: [".xml", ".csv"],
    instructions: [
      "Open the Health app on your iPhone",
      "Tap your profile picture in the top right",
      "Scroll down and tap 'Export All Health Data'",
      "Save the export.zip file and upload it here",
    ],
  },
  {
    id: "fitbit",
    name: "Fitbit",
    icon: "📊",
    description: "Import your Fitbit activity data",
    fileTypes: [".json", ".csv"],
    instructions: [
      "Log in to your Fitbit account at fitbit.com",
      "Go to Settings > Data Export",
      "Request your data archive",
      "Download and upload the file here",
    ],
  },
  {
    id: "garmin",
    name: "Garmin",
    icon: "🏃",
    description: "Connect your Garmin device",
    fileTypes: [".fit", ".tcx", ".gpx"],
    instructions: [
      "Open Garmin Connect on your device",
      "Go to Settings > Account > Export Your Data",
      "Select the date range you want to export",
      "Download and upload the file here",
    ],
  },
  {
    id: "whoop",
    name: "WHOOP",
    icon: "💪",
    description: "Analyze your WHOOP recovery data",
    fileTypes: [".csv", ".json"],
    instructions: [
      "Open the WHOOP app",
      "Go to Settings > Export Data",
      "Select the metrics you want to export",
      "Download and upload the file here",
    ],
  },
  {
    id: "oura",
    name: "Oura Ring",
    icon: "💍",
    description: "Import your Oura sleep and activity data",
    fileTypes: [".json", ".csv"],
    instructions: [
      "Log in to cloud.ouraring.com",
      "Navigate to Settings > Personal Info",
      "Click 'Download Your Data'",
      "Upload the downloaded file here",
    ],
  },
  {
    id: "samsung",
    name: "Samsung Health",
    icon: "📱",
    description: "Sync Samsung Health data",
    fileTypes: [".csv", ".json"],
    instructions: [
      "Open Samsung Health app",
      "Tap Menu > Settings",
      "Select 'Download personal data'",
      "Upload the downloaded file here",
    ],
  },
]
